-- filepath: backend\09_zones_traffic_incidents.sql
-- New schema for zones + traffic + incidents + traffic_log (Davao reporting + map pins)
-- Run in Supabase Dashboard → SQL Editor.

-- =====================
-- ENUMS
-- =====================
DO $$ BEGIN
  CREATE TYPE public.incident_type_enum AS ENUM (
    'Accident',
    'Pedestrian Accident',
    'Breakdown',
    'Flooding',
    'Road Closure',
    'Construction',
    'Stalled Vehicle'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.incident_status_enum AS ENUM (
    'Reported',
    'In Progress',
    'Resolved',
    'Cancelled'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.traffic_status_enum AS ENUM (
    'Light',
    'Moderate',
    'Heavy',
    'Blocked'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- =====================
-- TABLES
-- =====================
CREATE TABLE IF NOT EXISTS public.zones (
  zone_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  district_name TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS public.traffic (
  traffic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id INT NOT NULL REFERENCES public.zones(zone_id) ON DELETE RESTRICT,
  traffic_status public.traffic_status_enum NOT NULL,
  reported_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  cancelled_at TIMESTAMPTZ,
  description TEXT
);

CREATE TABLE IF NOT EXISTS public.incidents (
  incident_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_type public.incident_type_enum NOT NULL,
  incident_status public.incident_status_enum DEFAULT 'Reported' NOT NULL,
  reported_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  resolved_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  description TEXT,
  cancelled_by UUID REFERENCES public.accounts(id) ON DELETE SET NULL,
  zone_id INT NOT NULL REFERENCES public.zones(zone_id) ON DELETE RESTRICT,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.traffic_log (
  traffic_log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_by UUID NOT NULL REFERENCES public.accounts(id) ON DELETE RESTRICT,
  traffic_id INT NOT NULL REFERENCES public.traffic(traffic_id) ON DELETE CASCADE
);

-- =====================
-- INDEXES
-- =====================
CREATE INDEX IF NOT EXISTS idx_zones_latlon ON public.zones(latitude, longitude);

CREATE INDEX IF NOT EXISTS idx_traffic_active ON public.traffic(cancelled_at);
CREATE INDEX IF NOT EXISTS idx_traffic_zone ON public.traffic(zone_id);

CREATE INDEX IF NOT EXISTS idx_incidents_active ON public.incidents(deleted_at, incident_status);
CREATE INDEX IF NOT EXISTS idx_incidents_zone ON public.incidents(zone_id);

CREATE INDEX IF NOT EXISTS idx_traffic_log_traffic ON public.traffic_log(traffic_id);
CREATE INDEX IF NOT EXISTS idx_traffic_log_updated_by ON public.traffic_log(updated_by);

-- =====================
-- RLS HELPERS
-- =====================
CREATE OR REPLACE FUNCTION public.current_account_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT a.id
  FROM public.accounts a
  WHERE a.auth_user_id = auth.uid()
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_account_role()
RETURNS public.account_role_enum
LANGUAGE sql
STABLE
AS $$
  SELECT a.role
  FROM public.accounts a
  WHERE a.auth_user_id = auth.uid()
  LIMIT 1;
$$;

-- =====================
-- ENABLE RLS
-- =====================
ALTER TABLE public.zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.traffic ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.traffic_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

-- =====================
-- POLICIES
-- =====================
-- Read access for authenticated users
DO $$ BEGIN
  CREATE POLICY "read zones" ON public.zones
  FOR SELECT TO authenticated
  USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "read traffic" ON public.traffic
  FOR SELECT TO authenticated
  USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "read incidents" ON public.incidents
  FOR SELECT TO authenticated
  USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "read traffic log" ON public.traffic_log
  FOR SELECT TO authenticated
  USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Zones: allow any authenticated user to insert (reporting creates a zone at the pin)
DO $$ BEGIN
  CREATE POLICY "insert zones" ON public.zones
  FOR INSERT TO authenticated
  WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Traffic: any authenticated user can report traffic
DO $$ BEGIN
  CREATE POLICY "insert traffic" ON public.traffic
  FOR INSERT TO authenticated
  WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Traffic log: allow inserts when updated_by matches the current account
DO $$ BEGIN
  CREATE POLICY "insert traffic log" ON public.traffic_log
  FOR INSERT TO authenticated
  WITH CHECK (updated_by = public.current_account_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Incidents: only CTTMO/ADMIN can report
DO $$ BEGIN
  CREATE POLICY "insert incidents (cttmo/admin)" ON public.incidents
  FOR INSERT TO authenticated
  WITH CHECK (public.current_account_role() IN ('CTTMO', 'ADMIN'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
